---
  - name: download cni-plugins
    ansible.builtin.get_url:
      url: https://github.com/containernetworking/plugins/releases/download/v1.0.0/cni-plugins-linux-{{architecture}}-v1.0.0.tgz
      dest: /tmp/cni-plugins.tgz.zip

  - name: ensure /opt/cni/bin
    ansible.builtin.file:
      path: /opt/cni/bin
      state: directory
      owner: "{{nomad_user_name}}"
      group: "{{nomad_user_name}}"

  - name: unzip cni-plugins
    ansible.builtin.unarchive:
      src:  /tmp/cni-plugins.tgz.zip
      dest: /opt/cni/bin
      remote_src: true

  - name: copy bridge conf
    ansible.builtin.copy:
      src: ../files/bridge.conf
      dest: /etc/sysctl.d/bridge.conf
      remote_src: false
      owner: "{{nomad_user_name}}"
      group: "{{nomad_user_name}}"