---

- name: nomad-base
  hosts: all
  become: true
  roles:
    - make_users
    - nomad-base

- name: setup server
  hosts: server
  become: true
  roles:
    - nomad-server

- name: setup client 
  hosts: client
  become: true
  roles:
    - nomad-client